input_dir: /nfs/research/marioni/asteif/projects/hbca/cellranger/2021-07-10

output_dir: /nfs/research/marioni/asteif/projects/hbca/genotyping/vireo/2021-07-10

reference_genome: /nfs/research/marioni/asteif/projects/hbca/reference/reference-2020-A/refdata-gex-GRCh38-2020-A/fasta/genome.fa

master_table: /nfs/research/marioni/asteif/projects/hbca/metadata/2021-08-10_master_table.csv

known_genotype_sample: SLX-20005-20446_SIGAE10

known_genotype_vcf: /nfs/research/marioni/asteif/projects/hbca/genotyping/haplotypecaller/2021-07-10/SLX-20005-20446_SIGAE10.haplotypecaller_pass_dbsnp.vcf

num_donors: 2

min_mapq: 40

random_seed: 42

num_threads: 16

sample_ids:
  - SLX-19647-20870_SIGAB8